### ISSUE TITLE
Some EEBus devices remain connected (and produce events) after calling CloseConnection

### ISSUE THREAD

**Issue by sthelen-enqs** [enbility/ship-go#32]
When connected to some EEBus devices, calling CloseConnection (as triggered through eebus-go's UnregisterRemoteSKI) doesn't completely tear down the SHIP/SPINE and the remote device continues providing read events.

I've attached a log with the DEBUG&TRACE loglevels as logged by eebus-go. UnregisterRemoteSKI is called on linke 15 which triggers the send of a "connectionClose" message to the remote device which appears to never confirm the connectionClose announcement and instead continues to provide measurement notifications.

Lines starting with "decoded: " trace calls of eebus-go functions/arguments.

[eebus_go_unregister_trimmed.log](https://github.com/user-attachments/files/16797143/eebus_go_unregister_trimmed.log)

I don't think we're doing anything "wrong" here per se (besides potentially accepting/forwarding events after sending a close notification), but we should probably adapt our logic to handle this case as well. We could potentially add a maxTime element to our closeConnection message and then trigger a timer after maxTime ms to call c.dataWriter.CloseDataConnection.

I could probably create a PR doing this, but we should maybe discuss what to set maxTime (or whether to make it configurable) etc.

**Comment by DerAndereAndi** [comment]
Thanks for the details. The reason is that the process details of SHIP 13.4.7.1.2 are not implemented. When closing the connection the stack does NOT set a maxtime and also doesn't implement a timer of the maximum allowed time to close the connection.

I would suggest to send a maxtime of 0 and close the connection 500ms after sending the request as it is done in if the stack receives an connection close announcement in [handshake.go line 18](https://github.com/enbility/ship-go/blob/dev/ship/handshake.go#L18-L33)
